---
name: Plugin Release
description: Releases the Buildkite Plugin
inputs:
  token:
    description: GitHub Token with contents write permissions
    required: true
  containerDigest:
    description: Container Image Digest
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --local user.email "${{ github.action }}+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch --tags
        git pull || true

    - name: Update Container Image
      if: inputs.containerDigest != ''
      shell: bash
      run: |
        sed -i "s/'quay.io\/muhlba91\/buildkite-agent.*'/'quay.io\/muhlba91\/buildkite-agent@${{ inputs.containerDigest }}'/g" lib/job.jsonnet
        git add lib/job.jsonnet

    - name: Versioning and Changelog
      id: versioning
      shell: bash
      run: |
        npx standard-version -i release-CHANGELOG.md \
          --skip.commit \
          --skip.tag \
          --skip.bump
        npx standard-version

        TAG_NAME=`git describe --abbrev=0 --match "v*"`
        echo ::set-output name=tagName::$(echo ${TAG_NAME})

    - name: Push Git Tag
      shell: bash
      run: |
        git push --follow-tags origin ${{ github.ref_name }}

    - name: GitHub Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: release-CHANGELOG.md
        name: ${{ steps.versioning.outputs.tagName }}
        tag: ${{ steps.versioning.outputs.tagName }}
        token: ${{ inputs.token }}
