---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{- if not (hasPrefix "@" (.Values.image.tag | default .Chart.AppVersion)) -}}:{{- end -}}{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: BUILDKITE_PLUGIN_KUBERNETES_SERVICE_ACCOUNT_NAME
              value: {{ include "agent.serviceAccountName" . }}
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "buildkite-agent-token" .Values.agentToken.existingSecretName }}
                  key: {{ default "buildkite-agent-token" .Values.agentToken.existingSecretKey }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_AGENT_TOKEN_SECRET_NAME
              value: {{ default "buildkite-agent-token" .Values.agentToken.existingSecretName }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_AGENT_TOKEN_SECRET_KEY
              value: {{ default "buildkite-agent-token" .Values.agentToken.existingSecretKey }}
            {{- if .Values.gitAuth.ssh.enabled }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_GIT_SSH_SECRET_NAME
              value: {{ default "git-auth-ssh" .Values.gitAuth.ssh.existingSecretName }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_GIT_SSH_SECRET_KEY
              value: {{ default "ssh-key" .Values.gitAuth.ssh.existingSecretKey }}
            {{- end }}
            {{- if .Values.gitAuth.credentials.enabled }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_GIT_CREDENTIALS_SECRET_NAME
              value: {{ default "git-auth-credentials" .Values.gitAuth.credentials.existingSecretName }}
            - name: BUILDKITE_PLUGIN_KUBERNETES_GIT_CREDENTIALS_SECRET_KEY
              value: {{ default "git-credentials" .Values.gitAuth.credentials.existingSecretKey }}
            {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.gitAuth.credentials.enabled .Values.gitAuth.ssh.enabled }}
          volumeMounts:
            - name: git-auth
              mountPath: /secrets
              readOnly: true
          {{- end }}
      volumes:
      {{- if or .Values.gitAuth.credentials.enabled .Values.gitAuth.ssh.enabled }}
        - name: git-auth
          projected:
            sources:
              {{- if .Values.gitAuth.credentials.enabled }}
              - secret:
                  name: {{ default "git-auth-credentials" .Values.gitAuth.credentials.existingSecretName }}
                  items:
                    - key: {{ default "git-credentials" .Values.gitAuth.credentials.existingSecretKey }}
                      path: git-credentials
                  mode: 256
              {{- end }}
              {{- if .Values.gitAuth.ssh.enabled }}
              - secret:
                  name: {{ default "git-auth-ssh" .Values.gitAuth.ssh.existingSecretName }}
                  items:
                    - key: {{ default "ssh-key" .Values.gitAuth.ssh.existingSecretKey }}
                      path: ssh-key
                  mode: 256
              {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
