{{- if and (not .Values.gitAuth.credentials.existingSecretName) .Values.gitAuth.credentials.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-auth-credentials
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  git-credentials: {{ .Values.gitAuth.credentials.value | b64enc }}
{{- end }}
