{{- if and (not .Values.gitAuth.ssh.existingSecretName) .Values.gitAuth.ssh.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-auth-ssh
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  ssh-key: {{ .Values.gitAuth.ssh.value | b64enc }}
{{- end }}
