{{- if not .Values.agentToken.existingSecretName }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: buildkite-agent-token
  labels:
    {{- include "buildscaler.labels" . | nindent 4 }}
data:
  buildkite-agent-token: {{ .Values.agentToken.value | b64enc }}
{{- end }}
