---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildscaler.fullname" . }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    {{- include "buildscaler.selectorLabels" . | nindent 6 }}
