---
replicaCount: 1

image:
  repository: quay.io/muhlba91/buildkite-agent
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

agentToken:
  value: buildkite-agent-token
  # existingSecretName: buildkite-secrets
  # existingSecretKey: buildkite-agent-token

gitAuth:
  credentials:
    enabled: true
    value: git-credentials
    # existingSecretName: buildkite-secrets
    # existingSecretKey: git-credentials
  ssh:
    enabled: true
    value: ssh-key
    # existingSecretName: buildkite-secrets
    # existingSecretKey: ssh-key

extraEnv: {}
  # ENV_VARIABLE: value

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# for example, check out https://github.com/elotl/buildscaler
# or use the provided Helm chart buildkite-buildscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: buildkite_busy_agent_percentage
        target:
          type: Value
          value: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 25
          periodSeconds: 600
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

nodeSelector: {}

tolerations: []

affinity: {}
